### ISSUE TITLE
Extension available already?

### ISSUE THREAD

**Issue by andrejilderda** [dalager/synology-scrobbler-ext#1]
Hi Christian,

Is this extension already available somewhere? Or can I maybe help you with testing?

Best regards,
Andre

**Comment by dalager** [comment]
I just pulled it of the chrome store as I had trouble getting it to work. The extension is not the problem, but rather the authorization through the backend. 
You can install the extension itself from disk using chromes "install unpacked extension" but you will need a backend.
I have the .NET backend in a private repos, that I can open source, if you're interested?
